name: 'OSS Wishlist Analyzer'
description: 'Analyze your project dependencies across all ecosystems (npm, PyPI, Cargo, Maven, etc.) using SBOM and ecosyste.ms data to identify sustainability risks'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  sbom-path:
    description: 'Path to SBOM file (SPDX JSON or CycloneDX JSON format)'
    required: false
    default: 'sbom.json'
  
  token:
    description: 'GitHub token for API access and commenting'
    required: true
    default: ${{ github.token }}
  
  dependency-threshold:
    description: '[DEPRECATED] This input is no longer used for filtering. All dependencies with wishlists are reported.'
    required: false
    default: '1000'
  
  create-issue:
    description: 'Create GitHub issue for high-risk dependencies'
    required: false
    default: 'false'
  
  comment-pr:
    description: 'Comment on PR with analysis results'
    required: false
    default: 'true'

outputs:
  with-wishlist-count:
    description: 'Number of dependencies with wishlists (currently GitHub Sponsors)'
  
  without-backing-count:
    description: 'Number of dependencies with wishlists but without Big Tech backing'
  
  report-path:
    description: 'Path to detailed analysis report'

runs:
  using: 'node20'
  main: 'dist/index.js'
