name: 'OSS Wishlist Analyzer'
description: 'Analyze your project dependencies across all ecosystems (npm, PyPI, Cargo, Maven, etc.) using SBOM and ecosyste.ms data to identify sustainability risks'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  sbom-path:
    description: 'Path to SBOM file (SPDX JSON or CycloneDX JSON format)'
    required: false
    default: 'sbom.json'
  
  token:
    description: 'GitHub token for API access and commenting'
    required: true
    default: ${{ github.token }}
  
  dependency-threshold:
    description: '[DEPRECATED] This input is no longer used for filtering. All dependencies with wishlists are reported.'
    required: false
    default: '1000'
  
  create-issue:
    description: 'Create GitHub issue for high-risk dependencies'
    required: false
    default: 'false'
  
  comment-pr:
    description: 'Comment on PR with analysis results'
    required: false
    default: 'true'

  # Optional filtering by OpenSSF Scorecard
  filter-scorecard:
    description: 'Filter results by OpenSSF Scorecard overall score range'
    required: false
    default: 'false'
  scorecard-min:
    description: 'Minimum OpenSSF Scorecard score (0.0 - 10.0)'
    required: false
    default: '7.0'
  scorecard-max:
    description: 'Maximum OpenSSF Scorecard score (0.0 - 10.0)'
    required: false
    default: '10.0'

  # Optional filtering by OpenSSF Criticality Score (if available)
  filter-criticality:
    description: 'Filter results by OpenSSF Criticality score range (requires metric availability)'
    required: false
    default: 'false'
  criticality-min:
    description: 'Minimum OpenSSF Criticality score (0.0 - 1.0)'
    required: false
    default: '0.70'
  criticality-max:
    description: 'Maximum OpenSSF Criticality score (0.0 - 1.0)'
    required: false
    default: '1.0'

  # Include Big Tech–backed dependencies
  include-bigtech-backed:
    description: 'Include dependencies with Big Tech backing (opt-in). If false, only show packages without Big Tech backing.'
    required: false
    default: 'false'

outputs:
  with-wishlist-count:
    description: 'Number of dependencies with wishlists (currently GitHub Sponsors)'
  
  without-backing-count:
    description: 'Number of dependencies with wishlists but without maintainers using Big Tech email aliases'
  
  report-path:
    description: 'Path to detailed analysis report'

runs:
  using: 'node20'
  main: 'dist/index.js'
